name: Overwatch Data and AI Analysis

on:
  schedule:
    - cron: '0 16 * * *' # 한국 시간 매일 새벽 1시
  workflow_dispatch: # 수동 실행 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 google-generativeai

      - name: Run Scraper
        run: python scraper.py

      - name: Run Gemini Analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python analysis_gen.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add history.json heroes.json analysis.json
          git commit -m "Update Overwatch Data and Javis Analysis" || echo "No changes"
          git push
